### ISSUE TITLE
chapter03 error

### ISSUE THREAD

**Issue by pedx78** [arturmuller/developing-a-redux-edge#2]
When I start the chapter03 app, and click on Add Note button, below error occurs

`warning.js:36 Warning: Failed prop type: Invalid prop`notes[0].content`of type`object`supplied to`NotesList`, expected`string`.

```
in NotesList (created by Connect(NotesList))
in Connect(NotesList) (created by App)
in div (created by App)
in App
in ProviderprintWarning
...`
```

`invariant.js:38 Uncaught Invariant Violation: Objects are not valid as a React child 
(found: object with keys {dispatchConfig, _targetInst, isDefaultPrevented, isPropagationStopped, _dispatchListeners, 
...
Check the render method of`NotesList`.`

**Comment by arturmuller** [comment]
Thank you, @pedx78, for this correction as well. It is now fixed. 👍
